[package]
name = "dpscript"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
lazy_static = "1.4.0"
miette = { version = "7.2.0", features = ["fancy", "serde"] }
once_cell = "1.19.0"
peg = "0.8.2"
ron = "0.8.1"
semver = { version = "1.0.22", features = ["serde"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
thiserror = "1.0.59"
toml = "0.8.12"
tracing = "0.1.40"
