<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>dpir</string>
   </array>
  <key>name</key>
  <string>dpscript_ir</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.dpscript_ir</string>
  <key>uuid</key>
  <string>ae8328da-80d6-42c8-b2a2-03468f3b0819</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.dpscript_ir</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(func|define|command|argument|call)</string>
          <key>name</key>
          <string>keyword.dpscript_ir</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(^(\s+)?data)</string>
          <key>name</key>
          <string>keyword.dpscript_ir</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(copy|append|set|get|variable_alias)\b</string>
          <key>name</key>
          <string>entity.name.tag.dpscript_ir</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\$\b([A-Za-z_\x{0024}][\w\x{0024}]*))</string>
          <key>name</key>
          <string>entity.name.other.dpscript_ir</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([A-Za-z_\x{0024}][\w\x{0024}]*)</string>
          <key>name</key>
          <string>entity.name.dpscript_ir</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dpscript_ir</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\};)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dpscript_ir</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;|=|;|,|@|\+|\!|:|%)</string>
          <key>name</key>
          <string>punctuation.dpscript_ir</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&apos;)</string>
          <key>name</key>
          <string>string.dpscript_ir</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.dpscript_ir</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.dpscript_ir</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.dpscript_ir</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\(|\)|\{|\}|\[|\])</string>
          <key>name</key>
          <string>punctuation.dpscript_ir</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.dpscript_ir</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.dpscript_ir</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
