<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>dps</string>
   </array>
  <key>name</key>
  <string>dpscript</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.dpscript</string>
  <key>uuid</key>
  <string>dbaa50d5-d092-4812-8401-2a0cf1f55e99</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(fn|module|import|const|let|for|if|objective|facade|id|path|return|init|tick|in|pub|compiler|enum|sub|goto)</string>
          <key>name</key>
          <string>keyword.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(storeof|keyof)</string>
          <key>name</key>
          <string>support.function.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(str|component|selector|Identifier|NBTPath|float|int|str|double|bool|dummy|NBT|Selector|Component|store|player)\b</string>
          <key>name</key>
          <string>entity.name.type.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([a-z_\x{0024}][\w\x{0024}]*)\b(\()</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.dpscript</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.dpscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([a-z_\x{0024}][\w\x{0024}]*)</string>
          <key>name</key>
          <string>entity.name.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([A-Z][\w\$]*)</string>
          <key>name</key>
          <string>entity.name.type.dpscript</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dpscript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\};)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.dpscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([\x{003b}.\x{002c}\x{003a}\x{0026}-\x{003e}\x{003c}\x{0023}]+)</string>
          <key>name</key>
          <string>punctuation.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;|=|;|,)</string>
          <key>name</key>
          <string>punctuation.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-&gt;)</string>
          <key>name</key>
          <string>punctuation.dpscript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.dpscript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.dpscript</string>
          <key>end</key>
          <string>([^\x{005c}]\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.dpscript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\(|\)|\{|\}|\[|\]|\.|#|\+|\*|\-|\/[^\/])</string>
          <key>name</key>
          <string>punctuation.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.dpscript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.dpscript</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.dpscript</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
