<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>iro</string>
   </array>
  <key>name</key>
  <string>iro</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.iro</string>
  <key>uuid</key>
  <string>e0fbbdae-90c3-466f-a089-6436289cb493</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>\b(styles|contexts)</string>
          <key>name</key>
          <string>keyword.iro</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b(name|file_extensions|textmate_uuid|regex|color|ace_scope|textmate_scope|pygments_scope|include|pattern|style|context)</string>
          <key>name</key>
          <string>support.function.iro</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([a-z_\x{0024}][\w\x{0024}]*)</string>
          <key>name</key>
          <string>entity.name.iro</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>((\\)?=)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.iro</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.iro</string>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.iro</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.iro</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.iro</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.iro</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.iro</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\};)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.iro</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([\x{003b}.\x{002c}\x{003a}\x{0026}-\x{003e}\x{003c}\x{0023}]+)</string>
          <key>name</key>
          <string>punctuation.iro</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;|=|;|,)</string>
          <key>name</key>
          <string>punctuation.iro</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\(|\)|\{|\}|\[|\]|\.|\+|\*|\-|\\|\||:)</string>
          <key>name</key>
          <string>punctuation.iro</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(^(\s+)?#.*)</string>
          <key>name</key>
          <string>comment.iro</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.iro</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.iro</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
